name: Check Approvals

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every 2 minutes

jobs:
  check-approvals:
    runs-on: ubuntu-latest
    steps:
    - name: Call Check Approvals API
      env:
        CRON_SECRET: ${{ secrets.CRON_SECRET }}
        API_URL: ${{ secrets.API_URL }}
      run: |
        curl -X GET \
          -H "Authorization: Bearer $CRON_SECRET" \
          $API_URL